{% set name = "wagtail-surveyjs" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail-surveyjs-{{ version }}.tar.gz
  sha256: 391ec69b8a9ad29fc93d90ee29fcc6db59c21c1f9eff93df38346c1d2ee2127a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - wagtail >=4.2.2

test:
  imports:
    - wagtailsurveyjs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wmo-raf/wagtail-surveyjs
  summary: Integrate SurveyJS in Wagtail Projects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
